language: csharp
sudo: required
mono: none
dist: xenial
dotnet: 3.0
  
# Define the jobs
jobs:
    include:
      - stage: "Build"
        script: 
        - dotnet build
        name: "Source"
        
      - stage: "Tests"
        script: 
        - dotnet test
        name: "Tests"
